runtime: custom
api_version: 1
env: flex
service: api

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

skip_files:
  - client/
  - nginx/
  - node_modules/

env_variables:
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_HOST: /cloudsql/randomuser-giga:southamerica-east1:randomuser-db
  ASSET_HOST: ${ASSET_HOST}
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}

beta_settings:
  cloud_sql_instances: randomuser-giga:southamerica-east1:randomuser-db
