version: "3"
services:
  postgres:
    image: postgres:alpine
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=randomuser
    expose:
      - "5432"

  api:
    build:
      context: .
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    container_name: randomuser_api
    env_file: .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=randomuser
    expose:
      - "3000"
    depends_on:
      - postgres

  client:
    build: ./client
    container_name: randomuser_client
    expose: 
      - "3000"

  proxy:
    build: ./nginx
    container_name: randomuser_proxy
    links:
      - api
      - client
    ports:
      - 80:80