version: "3"
services:
  postgres:
    image: postgres:alpine
    expose:
      - "5432"

  api:
    build:
      context: .
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    container_name: randomuser_api
    ports:
      - 3030:3000
    expose:
      - "3000"
    depends_on:
      - postgres

  client:
    build: ./client
    container_name: randomuser_client
    expose: 
      - "3000"

  proxy:
    build: ./nginx
    container_name: randomuser_proxy
    links:
      - api
      - client
    ports:
      - 80:80