version: "3"
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432

  api:
    build: .
    container_name: randomuser_api
    expose:
      - "3000"
    depends_on:
      - postgres

  client:
    build: ./client
    container_name: randomuser_client
    expose: 
      - "3000"

  proxy:
    build: ./nginx
    container_name: randomuser_proxy
    links:
      - api
      - client
    ports:
      - 80:80